# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image_path',
        ),
        migrations.AddField(
            model_name='notice',
            name='photo',
            field=models.ImageField(default='http://placehold.it/350x150', upload_to='notice'),
        ),
    ]
