# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_exam_mock_news_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
