# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20170217_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_id', models.CharField(max_length=30)),
                ('student_title', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('student_photo', models.ImageField(default='', upload_to='testimonial/student')),
                ('background', models.ImageField(default='', upload_to='testimonial/bg')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
