# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170302_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='background',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prere',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_photo',
        ),
        migrations.RemoveField(
            model_name='course',
            name='text',
        ),
    ]
