# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170302_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='course',
            name='background',
            field=models.ImageField(default='settings.MEDIA_ROOT/course/bg/default_course.jpg', upload_to='course/bg'),
        ),
        migrations.AddField(
            model_name='course',
            name='features_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='course',
            name='methodology_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='course',
            name='needfor_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='course',
            name='objective_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
