# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170303_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='strengths_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
