# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_course_strengths_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_course',
            field=models.BooleanField(default=False),
        ),
    ]
