# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_course_featured_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
