# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_stream_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='background',
            field=models.ImageField(default='/course/bg/default_course.jpg', help_text='Please upload an image of dimensions : width = 290px & height = 150px only', upload_to='course/bg'),
        ),
    ]
