# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170303_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='about_text',
            new_name='details_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='features_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='methodology_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='needfor_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='objective_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overview_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='strengths_text',
        ),
        migrations.AlterField(
            model_name='course',
            name='background',
            field=models.ImageField(default='course/bg/default_course.jpg', help_text='Please upload an image of dimensions : width = 290px & height = 150px only', upload_to='course/bg'),
        ),
    ]
