# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170306_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='details_text',
            field=models.TextField(blank=True, max_length=30000),
        ),
    ]
