# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20170306_2218'),
        ('posts', '0017_auto_20170303_1327'),
    ]

    operations = [
    ]
