# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20170306_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='question_paper_url',
            field=models.CharField(default='', help_text='Please enter the question paper link.', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_url',
            field=models.CharField(default='', help_text='Please enter the youtube url of the video.', max_length=200),
        ),
    ]
