# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20170307_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('featured_result', models.BooleanField(default=False)),
                ('details_text', models.TextField(blank=True, max_length=30000)),
                ('highlight_text', models.TextField(blank=True, max_length=3000)),
                ('background', models.ImageField(default='results/bg/default_result.jpg', help_text='Please upload an image of dimensions : width = 290px & height = 150px only', upload_to='results/bg')),
                ('batch', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.CourseCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_scorer_id', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=50)),
                ('student_title', models.CharField(max_length=50)),
                ('student_photo', models.ImageField(default='', upload_to='results/student')),
                ('batch', models.CharField(blank=True, max_length=50)),
                ('featured_top_scorer', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Course')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Result')),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Course'),
        ),
    ]
