# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20170307_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.FileField(default='', help_text='Please upload the course related documents only', upload_to='course/documents'),
        ),
    ]
