# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20170307_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Document'),
        ),
    ]
