# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20170307_1514'),
        ('posts', '0019_merge_20170307_0955'),
    ]

    operations = [
    ]
