# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20170307_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='youtube_url',
            field=models.CharField(blank=True, default='', help_text='Please enter the youtube url of the video.', max_length=200),
        ),
    ]
