# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_merge_20170308_1100'),
        ('posts', '0027_auto_20170308_1730'),
    ]

    operations = [
    ]
