# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20170309_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
