# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20170309_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address',
        ),
        migrations.AddField(
            model_name='center',
            name='address_line1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='center',
            name='address_line2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='center',
            name='address_line3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='center',
            name='address_line4',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
