# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20170309_1835'),
        ('posts', '0028_merge_20170308_1824'),
    ]

    operations = [
    ]
