# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20170309_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Document'),
        ),
        migrations.AddField(
            model_name='notice',
            name='youtube_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(default='', upload_to='notice'),
        ),
    ]
