# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20170314_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='youtube_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
