# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0035_auto_20170314_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(blank=True, default='support@tandemglobal.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+91 484-3040175', max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('address_line3', models.CharField(blank=True, max_length=300)),
                ('address_line4', models.CharField(blank=True, max_length=300)),
                ('twitter_url', models.CharField(blank=True, default='', max_length=255)),
                ('facebook_url', models.CharField(blank=True, default='', max_length=255)),
                ('google_url', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=255)),
                ('youtube_channel_url', models.CharField(blank=True, default='', max_length=255)),
                ('mission_text', models.TextField(blank=True, max_length=3000)),
                ('vision_text', models.TextField(blank=True, max_length=3000)),
                ('aboutus_text', models.TextField(blank=True, max_length=3000)),
                ('partner_text', models.TextField(blank=True, max_length=3000)),
                ('company_info', models.TextField(blank=True, max_length=3000)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('years_caption', models.CharField(blank=True, max_length=10)),
                ('background', models.ImageField(default='', upload_to='slider/bg')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
