# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_siteconfiguration_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_line3',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address_line4',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(blank=True, default='2ND FLOOR, STR COMPLEX,\n VEEKSHANAM ROAD, \n OPP. INTERNATIONAL HOTEL, \n ERNAKULAM 682035.', max_length=300),
        ),
    ]
