# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_auto_20170315_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='author',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='slider_background',
            field=models.ImageField(default='', upload_to='slider/bg'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='slider_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='slider_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='slider_years_caption',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='facebook_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='google_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='twitter_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='youtube_channel_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
