# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_auto_20170315_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='details_text',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
