# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_merge_20170309_1906'),
        ('posts', '0043_auto_20170315_1450'),
    ]

    operations = [
    ]
