# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_merge_20170316_1014'),
        ('posts', '0044_auto_20170318_1420'),
    ]

    operations = [
    ]
