# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_auto_20170318_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_info_footer',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='aboutus_text',
            field=models.TextField(blank=True, max_length=8000),
        ),
    ]
