# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_merge_20170318_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='aboutus_text',
            field=models.TextField(blank=True, max_length=8000),
        ),
    ]
