# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_auto_20170321_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_logo',
            field=models.ImageField(default='logo/eduexcel-logo.png', upload_to='logo'),
        ),
    ]
