# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0046_siteconfiguration_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cousre_details_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('details_text', models.TextField(blank=True, max_length=100000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.CourseCategory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Course')),
            ],
        ),
    ]
