# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_coursedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='category',
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
