# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_auto_20170321_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetails',
            new_name='CourseDetail',
        ),
    ]
