# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_auto_20170321_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cousre_id',
            new_name='course_id',
        ),
    ]
