# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_auto_20170321_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='cousre_id',
        ),
    ]
