# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_auto_20170318_1648'),
        ('posts', '0051_auto_20170321_1737'),
    ]

    operations = [
    ]
