# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_auto_20170323_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
