# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_merge_20170323_1024'),
        ('posts', '0052_auto_20170323_1519'),
    ]

    operations = [
    ]
