# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_coursedetail_order'),
        ('posts', '0053_merge_20170323_1524'),
    ]

    operations = [
    ]
