# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_coursedetail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='mission_text',
            new_name='boards_message',
        ),
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='vision_text',
            new_name='training_methodology',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='boards_photo',
            field=models.ImageField(blank=True, default='methodology/board.jpg', upload_to='methodology'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='methodology_image',
            field=models.ImageField(blank=True, default='methodology/method.jpg', upload_to='methodology'),
        ),
        migrations.AlterField(
            model_name='slogan',
            name='icon',
            field=models.ImageField(blank=True, default='slogan/icon/teacher-teaching-with-a-stick.png', upload_to='slogan/icon'),
        ),
    ]
