# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_auto_20170323_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slogan',
            name='icon',
            field=models.ImageField(blank=True, default='slogan/icon/teacher-teaching-with-a-stick.png', help_text='Add an icon of dimensions 80px*80px', upload_to='slogan/icon'),
        ),
    ]
