# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_auto_20170323_1850'),
        ('posts', '0054_merge_20170323_1534'),
    ]

    operations = [
    ]
