# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_auto_20170324_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slogan',
            name='background',
            field=models.ImageField(blank=True, default='slogan/bg/slogan_bg.jpg', help_text='No need of separate background for each slogan. If adding, add a background of 1314*137px', upload_to='slogan/bg'),
        ),
    ]
