# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_auto_20170324_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slogan',
            name='background',
        ),
    ]
