# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_merge_20170323_1857'),
        ('posts', '0058_auto_20170324_2308'),
    ]

    operations = [
    ]
