# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_remove_slogan_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='popup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='popup_image',
            field=models.ImageField(default='home/popup.png', upload_to='home'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='popup_text',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='popup_title',
            field=models.CharField(blank=True, default='Attention', max_length=255),
        ),
    ]
