# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_merge_20170324_2311'),
        ('posts', '0059_remove_slogan_background'),
    ]

    operations = [
    ]
