# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_auto_20170327_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='popup_image',
            field=models.ImageField(default='home/popup.jpg', help_text='Please upload an image of dimensions : width = 400 px & height = 264px only', upload_to='home'),
        ),
    ]
