# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0061_auto_20170327_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='popup_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Popup in Home Page'),
        ),
    ]
