# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_merge_20170325_1456'),
        ('posts', '0062_auto_20170327_1243'),
    ]

    operations = [
    ]
