# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_auto_20170327_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
